// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNkqTObkD1LEx_ccknWrMpH8f9D3W8lv4',
    appId: '1:569906670096:web:4217bb7309fc9a899cb895',
    messagingSenderId: '569906670096',
    projectId: 'gumenix-428d9',
    authDomain: 'gumenix-428d9.firebaseapp.com',
    storageBucket: 'gumenix-428d9.firebasestorage.app',
    measurementId: 'G-MKW5YYE1K7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBorx4s8XOHMgIQS54bec9uxDp8biOg8w',
    appId: '1:569906670096:android:687a71d9ae3148469cb895',
    messagingSenderId: '569906670096',
    projectId: 'gumenix-428d9',
    storageBucket: 'gumenix-428d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYgtuLIbjnNnxrUKVt2hEw0M3HN9QJAUE',
    appId: '1:569906670096:ios:bafd3c9d041a635f9cb895',
    messagingSenderId: '569906670096',
    projectId: 'gumenix-428d9',
    storageBucket: 'gumenix-428d9.firebasestorage.app',
    iosBundleId: 'com.example.routexNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYgtuLIbjnNnxrUKVt2hEw0M3HN9QJAUE',
    appId: '1:569906670096:ios:bafd3c9d041a635f9cb895',
    messagingSenderId: '569906670096',
    projectId: 'gumenix-428d9',
    storageBucket: 'gumenix-428d9.firebasestorage.app',
    iosBundleId: 'com.example.routexNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNkqTObkD1LEx_ccknWrMpH8f9D3W8lv4',
    appId: '1:569906670096:web:a550ae7e91ac12329cb895',
    messagingSenderId: '569906670096',
    projectId: 'gumenix-428d9',
    authDomain: 'gumenix-428d9.firebaseapp.com',
    storageBucket: 'gumenix-428d9.firebasestorage.app',
    measurementId: 'G-1KD4VBD1ZM',
  );
}
